Added missing include in CrossThreadCall.h
In file included from firebreath-1.3.1/src/ScriptingCore/BrowserHost.h:297,
                 from firebreath-1.3.1/src/ScriptingCore/JSObject.h:20,
                 from firebreath-1.3.1/src/ScriptingCore/DOM/Element.h:20,
                 from firebreath-1.3.1/src/ScriptingCore/DOM/Element.cpp:15:
firebreath-1.3.1/src/ScriptingCore/CrossThreadCall.h: In static member function ‘static typename Functor::result_type FB::CrossThreadCall::syncCallHelper(const FB::BrowserHostPtr&, Functor, boost::true_type)’:
firebreath-1.3.1/src/ScriptingCore/CrossThreadCall.h:140: error: ‘scoped_ptr’ is not a member of ‘boost’
firebreath-1.3.1/src/ScriptingCore/CrossThreadCall.h:140: error: expected primary-expression before ‘>’ token
firebreath-1.3.1/src/ScriptingCore/CrossThreadCall.h:140: error: there are no arguments to ‘call’ that depend on a template parameter, so a declaration of ‘call’ must be available
firebreath-1.3.1/src/ScriptingCore/CrossThreadCall.h:140: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)